endpoint:
  url: https://walker-atesvc2017-qal-qdc.dckr.intuit.net/atesvc2017/#/monitoring
  method: GET
  timeout: 0.5
  expectation:
    - type: HTTP_STATUS
      status_range: 200-300
    - type: LATENCY
      threshold: 1
    - type: REGEX
      regex: '.*(<body).*'
  allowed_fails: 0
cachet:
  # api_url: http://localhost:80/api/v1
  api_url: http://206.189.69.189/api/v1
  token: mO8tnTWU59ZKmCbZVG9y
  component_id: 1
  # metric_id: 1
  action:
    - CREATE_INCIDENT
    - UPDATE_STATUS
  public_incidents: true
frequency: 30
latency_unit: ms
